title: "Santosh Kumar Singh"
description: "Principal Software Engineer â€” .Net, ML, AI"
url: "https://santoshk86.github.io" # Update if deploying under a custom domain
baseurl: "" # For user/organization pages, keep empty

theme: null
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Site-wide variables (edit as needed)
author:
  name: "Santosh Kumar Singh"
  email: "santosh.singh.20@gmail.com"
  location: "USA"
  role: "Principal Software Engineer"
  summary: "High-level technical leader responsible for driving software strategy, system architecture, and innovation across multiple teams or platforms."

social:
  linkedin: "https://www.linkedin.com/in/singhk86/"
  github: "https://github.com/santoshk86"
  stackoverflow: ""
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: page

# Exclude build artifacts
exclude:
  - README.md
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
